FROM node:18-slim
WORKDIR /app
ENV NODE_OPTIONS=--openssl-legacy-provider
EXPOSE 8080
COPY custom-assets/CustomTheme/nethserver.png /usr/share/lemonldap-ng/portal/htdocs/static/CustomTheme/nethserver.png
COPY custom-assets/CustomTheme/custom.css /usr/share/lemonldap-ng/portal/htdocs/static/CustomTheme/custom.css
COPY custom-assets/common/backgrounds/nethbackground.png /usr/share/lemonldap-ng/portal/htdocs/static/common/backgrounds/nethbackground.png
ENTRYPOINT ["./container-entrypoint.sh"]
