FROM node:18-slim
WORKDIR /app
ENV NODE_OPTIONS=--openssl-legacy-provider
EXPOSE 8080
COPY assets/apps/nethserver.png /usr/share/lemonldap-ng/portal/htdocs/static/CustomTheme/nethserver.png
COPY assets/css/custom.css /usr/share/lemonldap-ng/portal/htdocs/static/CustomTheme/custom.css
COPY assets/backgrounds/nethbackground.png /usr/share/lemonldap-ng/portal/htdocs/static/common/backgrounds/nethbackground.png
ENTRYPOINT ["./container-entrypoint.sh"]
